"""Cernora: evidence-bound evaluation for tool-using agents."""

from cernora.adapter import AdaptedBundle, Adapter, CompletedExport
from cernora.batch import (
    BatchAttempt,
    BatchAttemptDiagnostics,
    BatchAttemptResources,
    BatchEvaluationFile,
    BatchEvaluationPackage,
    BatchFailureCodeCount,
    BatchGroupSummary,
    BatchInput,
    BatchLifecycleRecord,
    BatchOutcomeCounts,
    BatchPlannedTrial,
    BatchRate,
    BatchSummary,
    BatchSummaryPackage,
    BatchTrial,
    build_batch_summary,
    embed_evaluation_package,
    materialize_batch_input,
    reload_batch_summary,
    reload_batch_summary_package,
    summarize_batch,
    validate_batch_input,
)
from cernora.comparison import (
    BootstrapPlan,
    ComparisonArm,
    ComparisonCase,
    ComparisonEstimate,
    ComparisonGuardrail,
    ComparisonInput,
    ComparisonInterval,
    ComparisonSummary,
    ComparisonSummaryPackage,
    ExperimentAuthority,
    ExperimentProjection,
    FailureMigration,
    GuardrailResult,
    OutcomeTransition,
    PassKPlan,
    PassMetric,
    PrimaryOutcome,
    PrimaryResult,
    Treatment,
    TreatmentChange,
    build_comparison_summary,
    evaluation_policy_sha256,
    materialize_comparison_input,
    materialize_experiment_authority,
    materialize_treatment,
    reload_comparison_package,
    reload_comparison_summary,
    render_comparison_summary_markdown,
    summarize_comparison,
    validate_comparison_input,
)
from cernora.conformance import (
    AdapterConformance,
    ConformanceError,
    ProfileConformance,
    check_adapter_conformance,
    check_profile_conformance,
)
from cernora.core.case import (
    Case,
    CaseInput,
    CaseProfile,
    FixtureReference,
    GatePolicy,
    ScorerPolicy,
)
from cernora.core.evidence import (
    AnswerClaim,
    Artifact,
    Evidence,
    EvidenceReference,
    Failure,
    ProcessResult,
    StructuredAnswer,
    ToolAction,
)
from cernora.core.evidence_bundle_v2 import EvidenceBundleV2
from cernora.core.gate import GateDecision
from cernora.core.identity import (
    ComponentIdentity,
    ExternalProducerIdentity,
    component_identity,
    external_producer_identity,
)
from cernora.core.result import EvaluationReport, ResultRecord
from cernora.core.score import Score, ScoreObservation
from cernora.evaluation.package import (
    evaluate_imported_case,
    read_evaluation_report,
    read_imported_evaluation,
)
from cernora.ingestion.contracts_v2 import AuthorityBoundImportPackageV2
from cernora.ingestion.package_v2 import import_evidence_bundle_v2
from cernora.metrics import (
    ArgumentMatch,
    FactMatch,
    Latency,
    Metric,
    MetricBinding,
    MetricContext,
    MetricDefinition,
    MetricPlan,
    ToolCalls,
    ToolSelection,
)
from cernora.profile import Profile, ProfileAssessment, ProfileEvaluationContext
from cernora.profile_loader import ProfileLoadError, load_local_profile
from cernora.profile_testing import (
    ProfileTestCase,
    ProfileTestCaseResult,
    ProfileTestError,
    ProfileTestSummary,
    run_profile_tests,
)
from cernora.profile_workspace import ProfileInitResult, ProfileWorkspaceError, init_profile
from cernora.resources import PUBLIC_SCHEMAS, read_public_schema

__version__ = "0.1.4"

__all__ = [
    "PUBLIC_SCHEMAS",
    "AdaptedBundle",
    "Adapter",
    "AdapterConformance",
    "AnswerClaim",
    "Artifact",
    "AuthorityBoundImportPackageV2",
    "BatchAttempt",
    "BatchAttemptDiagnostics",
    "BatchAttemptResources",
    "BatchEvaluationFile",
    "BatchEvaluationPackage",
    "BatchFailureCodeCount",
    "BatchGroupSummary",
    "BatchInput",
    "BatchLifecycleRecord",
    "BatchOutcomeCounts",
    "BatchPlannedTrial",
    "BatchRate",
    "BatchSummary",
    "BatchSummaryPackage",
    "BatchTrial",
    "BootstrapPlan",
    "Case",
    "CaseInput",
    "CaseProfile",
    "ComparisonArm",
    "ComparisonCase",
    "ComparisonEstimate",
    "ComparisonGuardrail",
    "ComparisonInput",
    "ComparisonInterval",
    "ComparisonSummary",
    "ComparisonSummaryPackage",
    "CompletedExport",
    "ComponentIdentity",
    "ConformanceError",
    "EvaluationReport",
    "Evidence",
    "EvidenceBundleV2",
    "EvidenceReference",
    "ExperimentAuthority",
    "ExperimentProjection",
    "ExternalProducerIdentity",
    "Failure",
    "FailureMigration",
    "FixtureReference",
    "GateDecision",
    "GatePolicy",
    "GuardrailResult",
    "OutcomeTransition",
    "PassKPlan",
    "PassMetric",
    "PrimaryOutcome",
    "PrimaryResult",
    "ProcessResult",
    "Profile",
    "ProfileAssessment",
    "ProfileConformance",
    "ProfileEvaluationContext",
    "ProfileInitResult",
    "ProfileLoadError",
    "ProfileTestCase",
    "ProfileTestCaseResult",
    "ProfileTestError",
    "ProfileTestSummary",
    "ProfileWorkspaceError",
    "ResultRecord",
    "Score",
    "ScoreObservation",
    "ScorerPolicy",
    "StructuredAnswer",
    "ToolAction",
    "Treatment",
    "TreatmentChange",
    "__version__",
    "build_batch_summary",
    "build_comparison_summary",
    "check_adapter_conformance",
    "check_profile_conformance",
    "component_identity",
    "embed_evaluation_package",
    "evaluate_imported_case",
    "evaluation_policy_sha256",
    "external_producer_identity",
    "import_evidence_bundle_v2",
    "init_profile",
    "load_local_profile",
    "materialize_batch_input",
    "materialize_comparison_input",
    "materialize_experiment_authority",
    "materialize_treatment",
    "read_evaluation_report",
    "read_imported_evaluation",
    "read_public_schema",
    "reload_batch_summary",
    "reload_batch_summary_package",
    "reload_comparison_package",
    "reload_comparison_summary",
    "render_comparison_summary_markdown",
    "run_profile_tests",
    "summarize_batch",
    "summarize_comparison",
    "validate_batch_input",
    "validate_comparison_input",
]

__all__ += [
    "ArgumentMatch",
    "FactMatch",
    "Latency",
    "Metric",
    "MetricBinding",
    "MetricContext",
    "MetricDefinition",
    "MetricPlan",
    "ToolCalls",
    "ToolSelection",
]
